services:
  app:
    image: web-app-develop-golang-todo
    build:
      args:
        - target=local
    environment:
      TODO_ENV: local
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
